---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oidc
resources:
  - ./authentik.yaml
  - ./ingress.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik