---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-csi-driver
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: hcloud-csi-driver
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: mlohr-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    ## Controller configuration
    controller:
      ## hcloud-csi-driver Docker image for controller containers
      image: hetznercloud/hcloud-csi-driver:1.6.0
      ## ImagePullPolicy for the hcloud-csi-driver Docker image
      imagePullPolicy: IfNotPresent
    ## Node configuration
    node:
      ## hcloud-csi-driver Docker image for node containers
      image: hetznercloud/hcloud-csi-driver:1.6.0
      ## ImagePullPolicy for the hcloud-csi-driver Docker image
      imagePullPolicy: IfNotPresent
      ## (host) path to kubelet lib dir
      kubeletPath: /var/lib/kubelet
    ## Settings for the StorageClass resource to be created.
    storageClass:
      ## Name of the StorageClass to be created.
      name: hcloud-volumes
      ## Should the StorageClass be annotated as default storage class?
      isDefault: true
      ## The reclaimPolicy that the StorageClass should use
      reclaimPolicy: "Delete"
    ## secret for the Hetzner Cloud API token
    secret:
      # Set this name to use an existing secret.
      # Keep it empty to have a secret generated by this chart.
      existingSecretName: hcloud
    ## Metrics configuration
    metrics:
      ## Enable metrics (create exporters etc.)
      enabled: false