apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 6h
  chart:
    spec:
      chart: vault
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    global:
      enabled: false
    server:
      enabled: "true"
      image:
        repository: "hashicorp/vault"
        tag: "1.13.1"
        pullPolicy: IfNotPresent
      updateStrategyType: "RollingUpdate"
      logFormat: "json"
      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - host: vault.robotwizard.co.uk
          paths: 
            - /
        # - host: vault.domain
        #   paths:
        #     - /
      tls: 
        - secretName: robotwizard-vault
          hosts:
            - vault.robotwizard.co.uk
    dataStorage:
      enabled: true
      size: 10Gi
      mountPath: "/vault/data"
      storageClass: hcloud-volumes
      accessMode: ReadWriteOnce
    standalone:
        enabled: "true"
        config: |
          ui = true
          cluster_name = "robotwizard"
          storage "file" {
            path = "/vault/data"
          }
          # HTTPS listener
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = 1
          }