apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:GG+vCUY=,iv:rtrip+skzKmUudTUeza6/H4v1nF6eCXBX3R9iPdeETo=,tag:y64UiITzV4O9i3sY1/ruKw==,type:str]
    password: ENC[AES256_GCM,data:YLKnJrjNc3ufv3t0wEvvd6nv4qXbLo7KhV0nypN7ZC0=,iv:uty4IbJFRYOqM0eYA5iUu+ViDPNw08g0+Cqn8vlSEq4=,tag:XsQXgN4YB4IeDSIkkiKVfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WWtpeEVPbmpOVUVTOURP
            NHZ4RW1CeUllekh3d1A0Y1lFL0w3ZnZyZFU0CjA0b0NSUHZDeVFTNkJFeVpaUkhV
            eVlySE9iejh1ejRMaytSWmczK2M5RlEKLS0tIHV5cEN4RnZCTDVQQnNWTjZFU2FU
            QmdHcU5VKzdNOW5sZnV1WmF1eXBsWGMK87jgNEThpcMwmgqnUHrhOFkVlxZy1Xdd
            mKXbSrnWOg5qtoYFB1JwhvBulBuAmqCF8lXbfV2qAd6HvAD+y4RLpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T20:50:11Z"
    mac: ENC[AES256_GCM,data:Phv1Myeb/x9v7+la0MzIMdgVPM/TLybQlZRIS+BjsWLB2S1xxwjAKfHYf26RepjPxaRYm7nnxZllFJ95kkKbftdrVg2HUOThxl5X0vcqJ8FxVJzkoiEvj7heO1CxRijzuCbwrpDZyT5oIBgGvXX5BzrscrhM/2HUi65eB4B0HCU=,iv:S++6n801vJ5DhYIOC8jfWnmgld2m6oiPQKZXM+MZelg=,tag:rEhsMgaEc6IYwAqSKOzdWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
