---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-csi-driver
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: hcloud-csi-driver
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: mlohr-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    secret:
      existingSecretName: hetzner-api