---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vault
  namespace: kube-system
spec:
  path: ./kubernetes/apps/kube-system/vault/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m