apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:
            - squirrelmentality.co.uk
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:            
            - robotwizard.co.uk
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:
            - hacksm.net
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:
            - matt-white.co.uk
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:
            - squirrelmentality.co.uk
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:            
            - robotwizard.co.uk
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:
            - hacksm.net
      - dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAW4YYMLNFHLSLCLZX
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-access-key
        selector:
          dnsZones:
            - matt-white.co.uk