---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2023.5.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.5.3
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: authentik.robotwizard.co.uk
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - authentik.robotwizard.co.uk
          secretName: robotwizard-authentik
    resources:
      server:
        requests: 
          cpu: 200m
        limits: 
          cpu: "2"
    geoip:
      enabled: false
    authentik:

      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

      postgresql:
        host: '{{ .Release.Name }}-postgresql'
        name: authentik
        user: authentik
      redis:
        host: '{{ .Release.Name }}-redis-master'

    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: hcloud-volumes
      postgresqlUsername: authentik
      postgresqlDatabase: authentik
    redis:
      enabled: true
      auth:
        enabled: true
      # global:
      #   storageClass: hcloud-volumes