---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.26
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    ingress:
      enabled: true
      className: nginx
      annotations:
        # hajimari.io/icon: sawtooth-wave
        # external-dns.alpha.kubernetes.io/hostname: ingress.squirrelmentality.co.uk
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
        - hosts:
            - ops.robotwizard.co.uk
          secretName: ops-cert
      rules:
      - host: ops.robotwizard.co.uk
        http:
          paths:
          - backend:
              service:
                name: weave-gitops
                port:
                  number: 9001
            path: /
            pathType: Prefix
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth