apiVersion: v1
kind: Secret
metadata:
    name: authentik-redis
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:E0UR/Fctoixka55Ki0nCQ3jXBD2e2VGTpjMMTlCyfzg=,iv:tgpDAs4+RqK3lyaV+16a6njNN609clInMm9XHSp1M+U=,tag:pWn1loO3ayYJJO6mVQkxYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVXJwa3VPWkpiZ2R1allG
            WWdBUzB4c2EwczlhZExxRk9LNEsrSVBRRmdjClhUc2d2V0RydUdUTUM0czlhaFVo
            NzVyT2xvbTJnUk5pNFQ4bnNrY1ZxdWcKLS0tIDRhbE1SQllVVkNoOGlmendLay9V
            OHdIaVN2Q2Fyd0FPL3dZd2Q0bUFvM0UKmP5AZ0t7/Tr1LFxbjTDEj6qB16lqGLm4
            kdeYGHVD4pQABgfyS4ZFKxqF/d/AlQko3b9ANhEHcI1JZ/rhv92b6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T20:03:54Z"
    mac: ENC[AES256_GCM,data:c7BYrUUZN0vjthajj/f/4Jgh/JXrDSiAaPWcBZeE+cZuFlm61RqtYRKwNfUSe9mDtimkf5ctcZ9o5iroQqywx5BvcgVjg/Q4uu5QMm+AwFq5J9QFB4Rf/z7i3+/19sslz1BwxAg68hRkTiaBtM5Ih9dm7o5g+4eISuTU4vfPlsU=,iv:+UZhGWyccyp5D1O/zHgBbqtQlFH1ywPD3oTtC/EfXys=,tag:acNxtg5sDdkkIW2vcF/r+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
