# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: kube-system
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:1Fr+/rwgHIBPHl+fHcSBdj/+aF37Ic8=,iv:2YTLoZVRnY6hlSQN3Uq/B6e9mWnDKIZMwU8FOpoAR2I=,tag:jUDFhNZ6lsLAONPy/H8kgw==,type:str]
    SECRET_PUBLIC_DOMAIN2: ENC[AES256_GCM,data:4RW1Sgu48rTI9kOxGBFJVVE=,iv:tJM/I3FT0PnSOYUwlziETB5f6GCP1vf9dA9NlLzDv2g=,tag:kg87h4iBXrHJi46p2kHpuQ==,type:str]
    SECRET_PUBLIC_DOMAIN3: ENC[AES256_GCM,data:VHpQSc8W4lPc9g==,iv:LeO3gDZx5DJ4As0YNQPHwvZP82VdGIWfZw+D331LfvM=,tag:qDsJwe6VhHk6dQMR7mcB2g==,type:str]
    SECRET_PUBLIC_DOMAIN4: ENC[AES256_GCM,data:MflO+CTjCEuWwpHMl1t/2A==,iv:5P1avpyqQK7oyvTsE4GztzwEJwKdXQan3OZTpXoqjmc=,tag:YbVSyt65NGV/NILm09TcUQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:k6QFwU5u38IVx4N0tMXccVqA6TPb,iv:HwExr+i4ZmnlevK2rKJa+KYH32dh4VofHRLCBEP5t5I=,tag:FcahcspqZr0MhtZ8RusA6Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:474108156746:key/bc5f3b08-70c6-4421-a8ee-f6fe32d94d6f
          created_at: "2023-05-28T22:04:25Z"
          enc: AQICAHj/+PwZrYiv+HkNp6sXnAQerEWUn8+hg6fmiGghYvJqmgHCyLotWIuM8FmXOgCOQN0wAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2WV1aVXznNi/esi6AgEQgDtUtAZDRQ4SMADpEIdTI8GXBusx4HEg8WwBcVq9fa5Wd+NAwqG3PazqOtZViS2FHj15nV5gp13ibqIBpA==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-28T22:04:25Z"
    mac: ENC[AES256_GCM,data:QLHNSdRxReJIeghrQjgWetnnXSI2/iiex+ojRMP2cSwUaOigj7C8TKraE6pqGeHw6/nXGuM5XiyFnLJ+d9cY3wKpuUvGb6egJEIR8+BgDHFQyWwrXrtGqGBYKcGQvritaePcF3tPYE629J+EQvqcyN/OZXNQKbjCrtGLeZm4o9M=,iv:a1da8kZJ65TVbhuXNYUjrBbIfGsX3VNxPK7DFX3Ja9k=,tag:tjjRNQBRWaqRwstbjR/fhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
