---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - helmrelease.yaml
  # - prometheusrule.yaml
  # - https://github.com/cert-manager/cert-manager/releases/download/v1.12.1/cert-manager.crds.yaml
configMapGenerator:
  - name: cert-manager-dashboard
    files:
      - cert-manager-dashboard.json=https://gitlab.com/uneeq-oss/cert-manager-mixin/-/raw/master/dashboards/cert-manager.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"