---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: utility
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: louislam/uptime-kuma
      tag: '1'
    env:
      TZ: "Europe/London"
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/server-snippets: |
            location / {
              proxy_set_header Upgrade $http_upgrade;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-Host $http_host;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $host;
              proxy_set_header Connection "upgrade";
              proxy_cache_bypass $http_upgrade;
            }
          hajimari.io/enable: "true"
          hajimari.io/appName: "Uptime"
          hajimari.io/icon: "update"
        hosts:
          - host: uptime.robotwizard.co.uk
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - uptime.robotwizard.co.uk
            secretName: uptime-cert
    persistence:
      data:
        enabled: true
        mountPath: /app/data
        storageClass: hcloud-volumes
        accessMode: ReadWriteMany
        size: 3Gi
        retain: true
    resources:
      requests:
        cpu: 100m
        memory: 52M
      limits:
        memory: 128M