apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgres
    namespace: authentik
stringData:
    postgresPassword: ENC[AES256_GCM,data:L3qXfGGRUcdbVgeMAPed4aPT2C5j37YsFOQuIT8in7jkINxFssJckFRLp1OL0uoY,iv:80Yi3RXdH3rARuyRk4hUz4uUMjZ0NwNqReaIhiPD1JQ=,tag:/D7qwTgN/rFYhhZErJF3+g==,type:str]
    password: ENC[AES256_GCM,data:HhWl5g==,iv:rA5POC1JOvESkSTmPmKGTsXDrd2pseys1NL72vguj2M=,tag:vuKYj7BwwNzu7hnjJxJ7jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZHErSC92b3lJU0tacWk5
            aXNEZDk2d3ZqQUgyakZkVFRzMlZHY2N0OVVNCk1ZZkZRbXRlMXUrWkVKS01YL2RY
            NjVNUmp2c1YyN0ppTTQvQkFIY0F0NlkKLS0tIEVoN0xyZkZNVWx1d1BqT0RHL1Ay
            b1lldHVZTVNuT1VlcDFuUHVST3R1K1EKGOmwEIEZw48WEreNxOolJDju/MGAu1oH
            dhOXOr6r2c4qZKXpmstf9WX5l85FAZZRopA/7XKCxRa+8nydbkSJhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T15:26:53Z"
    mac: ENC[AES256_GCM,data:pvr/7zsZNOgc12r0nBdElpar0ywwAfjQUD/wCcP4zPXN8n01H1+k5c6QBbnwQZ6Mv7bfQ6ax0g4uBV9Dsmhy6YhKzvYCc34iZphEXXDS+x+kVr5lTNXXwGeJOwKD3CnuJ2bLkfPUNtZ2TB9atOfPgFCXA9Z/jDuUil9erVVE5fA=,iv:u6OG9COY+i00py+6LpxYotsAOt6yVdTqJTrvH4ehhtI=,tag:c53wibL0zdoDHLl+1xz4Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
