# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:BqYcPHApH7dgWJ7wPOo2J8a9BRI8N8HYwettCSpqtFe6x4VV9Q1Q9DNbCwoeTMT4AptN1Cr5S03w6W1UIW3U8PV17kXak5rGHZFf0Qnyc/m/ElGE3Tqf93RaAf6mnuHjbfrjlCr2/H+aP2ujQOvamIK9gasTjwusBb/EVM5SLklT+83Otcq+pUfEu/+EljiKKYiVdPPtZ+fV5Xq+jYldBJ+sNI/7Ik8Ykn8xqeMxuttlMHCYZ3h1yKUWEZEzjDuJ9PAmUJlsDk/vU55tH0rsMaxDpQSdRvPvaB1UebrcDpLpff8e4stB56yXglHLCxPCV2sXL18iyJg4mPwDcC8T4p5mISnGe/H3eimedoWoTvmMSYPR/4PyXwhuv1BcbJuEtN7zl/lsh6hP+ShbaB/nknHj+BH45wFodUmtTQFc1OGSy81whS6fl8V3OLmG9FqexidCpXOszjRFwTInPby/rPCscr8oAyb9EHtdEkIACKSM/1kREO+5BCAYrS4HPRDpZv7BT+zJYwBez1orPlWXOBYGrwP0bEr9kpejrb81jl8CxoPWTZUS0BNAaoR9n6Upw+mEiPUQdn0G+y++V7NxGwj8Ymmt76ueuHmhNuQFxCEevYadl08xOx+sse9qShjBZ+olKq5rwbMaIOzN8C13vxjAffoN8FvOXdRyNZni9Vid5b8cTiS2vHERLSJzMljEt+WLLD4LuSad8pvxIUbbhAcOuOXwP892WcGK2hsArwZxZZm3wTBkCutTaKuzrzMIURrxpMNWSeWM2XZMxKB7ojI4XahLAzK+V92+9naWIWGC0W/Cmm1/wL3l8uxzpeGM9DSbW3jHmu39uug46kaFZbcq,iv:3pqXxrJ+52Y4mT+40tAd4urZ5GImagkBvxuWul8SzzQ=,tag:iyFROOCSjw9U/US37mUQtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRXc1eXRUeTArQWU5N0sw
            bHhXLy8yTEcwOE5PdWR1dHVyTjRiQkNJRUFVCndGd1JRc3A5SjRuNDh0ZlI2M29R
            ZlFoK3pmY2Y5SGVLbE9RcFBaTW95bzQKLS0tIEJKamkzUVY2SXdMRG50VEtEb2Ex
            RGhweVJ3OFA2NlJ2bjNib201UTdxZzAKwQkRGt2LKu5nohw9CuJTzuDN47CxxNiw
            ybiqkmisCcKhOjuz0PO3VOzorZTZrZyaIHU5CFGJfpVBJLiGXtkVCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T20:13:59Z"
    mac: ENC[AES256_GCM,data:K+AKXbeXB6aadrlXIg/YiisekH+rQhaTfcDjpaYiNWBbIkTIfXlMZkCAe11c+mUXqRiO1OWJtvuJwHy8RqeFiLZwlc+pV7v3hzAKQYTm15QlSngBxVIX2v17okHDHNiIG186dR+9E0YFpd21LnIccWMQIo2HwBGUHbD09ocDWpg=,iv:7U6iVRz8NSfHlfvqxB0pxWRobRM2E1QT5aHV9zy70pA=,tag:bTGbXG4w4/CPUpcI+Tri2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
