---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 7.0.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      resources:
        requests:
          memory: 105M
        limits:
          memory: 105M
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "gold.robotwizard.co.uk"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - gold.robotwizard.co.uk
            secretName: goldilocks-tls
      resources:
        requests:
          memory: 105M
        limits:
          memory: 105M